const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.List,
		C3.Plugins.TextBox,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.ScriptsInEvents.FolhaJogo_Event4_Act15,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.ScriptsInEvents.FolhaJogo_Event8_Act1,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.FolhaJogo_Event30_Act2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Interpolação: 0},
	{breno: 0},
	{chao_solid: 0},
	{coca_obj: 0},
	{texto_distancia: 0},
	{coca_point: 0},
	{Teclado: 0},
	{fundo2: 0},
	{fundo3: 0},
	{fundo4: 0},
	{chao: 0},
	{fundo_muro: 0},
	{bar: 0},
	{cadeira: 0},
	{jao: 0},
	{titulo: 0},
	{btStart: 0},
	{Mouse: 0},
	{texto_coca: 0},
	{dialogo_jao_incicial: 0},
	{Texto_Inicial: 0},
	{dialogo_breno_inicial: 0},
	{Texto_Breno_inicial: 0},
	{Audio: 0},
	{parede_solid: 0},
	{som: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{btTentarNovamente: 0},
	{bt_menu: 0},
	{Texto_hscore: 0},
	{fundo_pontuacao: 0},
	{Texto_pontuacao: 0},
	{pastel: 0},
	{mesaEcadeira: 0},
	{Sprite2: 0},
	{dialogo_pastel: 0},
	{Texto_pestel: 0},
	{chao_solid2: 0},
	{inimigo_generico: 0},
	{fumaca_briga: 0},
	{dialogo_caloteiro: 0},
	{Texto_caloteiro: 0},
	{Texto_inimigo: 0},
	{dialogo_inimigo: 0},
	{bt_sobre: 0},
	{Sprite4: 0},
	{offsetYValue: 0},
	{Texto_Historia: 0},
	{Lista: 0},
	{fundo_Texto_historia: 0},
	{EntradaDeTexto: 0},
	{texto_highscore: 0},
	{ArmazenamentoLocal: 0},
	{chao_cidade_2: 0},
	{muroFundo_cidade_2: 0},
	{fundo_cidade2_1: 0},
	{fundo_cidade2_2: 0},
	{fundo_cidade2_3: 0},
	{fundo_cidade2_4: 0},
	{fundo_cidade2_5: 0},
	{fundo_muro_cidade2: 0},
	{Toque: 0},
	{scrollSpeed: 0},
	{vidas: 0},
	{distancia: 0},
	{vivo: 0},
	{scrollbkp: 0},
	{frequencia: 0},
	{distancia_fumaca_x: 0},
	{fundo_numero: 0},
	{distancia_fumaca_y: 0},
	{last_obj: 0},
	{numero: 0},
	{dano: 0},
	{tipo_morte: 0},
	{highscore: 0}
];

self.InstanceType = {
	breno: class extends self.ISpriteInstance {},
	chao_solid: class extends self.ITiledBackgroundInstance {},
	coca_obj: class extends self.ISpriteInstance {},
	texto_distancia: class extends self.ISpriteFontInstance {},
	coca_point: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	fundo2: class extends self.ITiledBackgroundInstance {},
	fundo3: class extends self.ITiledBackgroundInstance {},
	fundo4: class extends self.ITiledBackgroundInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	fundo_muro: class extends self.ITiledBackgroundInstance {},
	bar: class extends self.ISpriteInstance {},
	cadeira: class extends self.ISpriteInstance {},
	jao: class extends self.ISpriteInstance {},
	titulo: class extends self.ISpriteInstance {},
	btStart: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	texto_coca: class extends self.ISpriteFontInstance {},
	dialogo_jao_incicial: class extends self.ISpriteInstance {},
	Texto_Inicial: class extends self.ITextInstance {},
	dialogo_breno_inicial: class extends self.ISpriteInstance {},
	Texto_Breno_inicial: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	parede_solid: class extends self.ITiledBackgroundInstance {},
	som: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	btTentarNovamente: class extends self.ISpriteInstance {},
	bt_menu: class extends self.ISpriteInstance {},
	Texto_hscore: class extends self.ITextInstance {},
	fundo_pontuacao: class extends self.ISpriteInstance {},
	Texto_pontuacao: class extends self.ITextInstance {},
	pastel: class extends self.ISpriteInstance {},
	mesaEcadeira: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	dialogo_pastel: class extends self.ISpriteInstance {},
	Texto_pestel: class extends self.ITextInstance {},
	chao_solid2: class extends self.ITiledBackgroundInstance {},
	inimigo_generico: class extends self.ISpriteInstance {},
	fumaca_briga: class extends self.ISpriteInstance {},
	dialogo_caloteiro: class extends self.ISpriteInstance {},
	Texto_caloteiro: class extends self.ITextInstance {},
	Texto_inimigo: class extends self.ITextInstance {},
	dialogo_inimigo: class extends self.ISpriteInstance {},
	bt_sobre: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto_Historia: class extends self.ITextInstance {},
	Lista: class extends self.IListInstance {},
	fundo_Texto_historia: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	texto_highscore: class extends self.ITextInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	chao_cidade_2: class extends self.ITiledBackgroundInstance {},
	muroFundo_cidade_2: class extends self.ITiledBackgroundInstance {},
	fundo_cidade2_1: class extends self.ITiledBackgroundInstance {},
	fundo_cidade2_2: class extends self.ITiledBackgroundInstance {},
	fundo_cidade2_3: class extends self.ITiledBackgroundInstance {},
	fundo_cidade2_4: class extends self.ITiledBackgroundInstance {},
	fundo_cidade2_5: class extends self.ITiledBackgroundInstance {},
	fundo_muro_cidade2: class extends self.ITiledBackgroundInstance {},
	Toque: class extends self.IInstance {}
}